### ISSUE TITLE
Center the output

### ISSUE THREAD

**Issue by scarlyw** [xehoth/TruthTableGenerator#4]
The current input is not adjusted according to the length of the variable, which does not seem intuitive enough
![1637880026(1)](https://user-images.githubusercontent.com/25168174/143505531-64babbf7-4f24-42e5-9053-fc459ab60c96.jpg)

**Comment by xehoth** [comment]
Solved by [center the output #5](https://github.com/xehoth/TruthTableGenerator/pull/5).
